AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  GitHubOrganization:
    Type: String
    Description: Name of the GitHub Organization the lambda will work on
  GitHubToken:
    Type: String
    Description: API Token to access GitHub GraphQL API

Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WeeklyReport
      Handler: main
      Timeout: 180
      Runtime: go1.x
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 ? * MON *)
            Input: !Sub
              - '{ "organization": "${org}", "GitHubToken": "${token}" }'
              - { org: !Ref GitHubOrganization, token: !Ref GitHubToken }

